---
title: "Agencies in the US Federal Register"
date: "Last updated: `r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(dplyr)
library(tidyr)
library(purrr)
library(tidytext)
library(rvest)
library(robotstxt)
library(ggplot2)
library(ggraph)
library(igraph)
library(ochRe)
library(dutchmasters)
set.seed(2018)

theme_set(theme_grey() + 
            theme(panel.background = element_rect(fil = dutchmasters$little_street[[2]]),
                  panel.grid = element_blank(),
                  panel.grid.major.x = element_line(colour = dutchmasters$little_street[[11]])))
```

Playing around with some data for theming plots, trying out network graphs.

## Scraping agency names

Makes use of US Federal Register

```{r agency_list, cache=TRUE}
fed_reg_url <- "https://www.federalregister.gov"

if(!get_robotstxt(fed_reg_url) %>% grepl("\\/agencies")) {
  agencies <- paste0(fed_reg_url, "/agencies") %>% 
  read_html() %>% 
  html_node("ul#agency-list") %>% 
  html_nodes("li") %>% 
  html_attr("data-filter-live") %>% 
  data.frame("agency" = ., stringsAsFactors = FALSE)

  head(agencies, 10) %>% knitr::kable()
}
```

```{r agency_tokens}
tidy_agencies <- agencies %>% 
  unnest_tokens(word, agency) %>% 
  anti_join(stop_words, by = "word")

tidy_agency_bigram <- agencies %>% 
  unnest_tokens(bigram, agency, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ", remove = FALSE) %>% 
  filter(!(word1 %in% stop_words$word | word2 %in% stop_words$word))
```

### Single-word frequency

Showing the top 25 single words, highlighting some choice ones.

```{r agency_word_plot}
tidy_agencies %>% 
  count(word, sort = TRUE) %>% 
  slice(1:25) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col(aes(fill = word %in% c("enforcement", "defense",
                                  "intelligence", "security")),
           alpha = 1/1.2, show.legend = FALSE) +
  xlab(NULL) +
  scale_fill_dutchmasters(palette = "little_street") +
  coord_flip()
```

### Bigram frequency

And some choice relationships among the top 75 word pairs.

```{r agency_network, fig.width=10, fig.height=8}
tidy_agency_bigram %>% 
  count(word1, word2, sort = TRUE) %>% 
  slice(1:75) %>% 
  graph_from_data_frame() %>% 
  ggraph(layout = "fr") +
  geom_edge_arc(aes(alpha = n, width = n), 
                colour = dutchmasters$little_street[[6]],
                show.legend = FALSE) +
  geom_node_point(aes(colour = !(name %in% c("enforcement", "defense",
                                             "intelligence", "security"))),
                  size = rel(15), show.legend = FALSE) +
  geom_node_label(aes(label = name),
                  colour = dutchmasters$little_street[[5]],
                  fill = dutchmasters$little_street[[6]],
                  fontface = "bold", size = rel(2.75),
                  alpha = 1/1.2, vjust = 0.5) +
  scale_colour_dutchmasters(palette = "little_street") +
  theme_void() +
  theme(panel.background = element_rect(fill = dutchmasters$little_street[[2]]))
```


